apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice
  template:
    metadata:
      labels:
        app: microservice
    spec:
      containers:
        - name: microservice
          image: cr.gitlab.switch.ch/hslu/edu/bachelor-computer-science/devops/23hs01/g04/g04-wiki-game/wiki-game-api:0.0.1-SNAPSHOT
          imagePullSecrets:
             name: gitlab-registry
          ports:
            - containerPort: 8000
              protocol: TCP
          # resources:
          #   requests:
          #     cpu: 1m
          #     memory: 1Mi
          #   limits:
          #     cpu: 2m
          #     memory: 2Mi