kind: Kustomization

resources:
  - deployment_api.yaml
  - deployment_ui.yaml
  - service_api.yaml
  - service_ui.yaml
  - configmap.yaml
  - ./mongodb/
  - service_api-metrics.yaml
  # - ingress.yaml