apiVersion: v1
kind: Service
metadata:
  name: wikigame-metrics
  labels:
    app: wikigame-api
spec:
  type: ClusterIP
  selector:
    app: wikigame-api
  ports:
    - name: http
      protocol: TCP
      port: 8081
      targetPort: 8081