apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wikigame-ingress
spec:
  rules:
    - host: intg.wikigame.devops
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: wikigame-api-intg
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wikigame-ui-intg
                port:
                  number: 8080