kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
nameSuffix: -intg

resources:
- ../base
- ingress.yaml

patches:
- path: ./patches/patch_configmap_mongodb-config.yaml
images:
- name: registry.hub.docker.com/lasher23/wiki-game-api
  newTag: dd6e9282
- name: registry.hub.docker.com/lasher23/wiki-game-ui
  newTag: dd6e9282
