apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cluster-monitoring-ingress
  namespace: monitoring
spec:
  rules:
    - host: cluster-monitoring.devops
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cluster-grafana
                port:
                  number: 8082
    