apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wikigame-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - host: prod.wikigame.devops
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: wikigame-api-prod
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wikigame-ui-prod
                port:
                  number: 8080
