kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

nameSuffix: -prod

resources:
  - ../base
  - ingress.yaml

patches:
  - path: ./patches/patch_configmap_mongodb-config.yaml
  # - sealedsecret_gitlab_registry.yaml

