apiVersion: v1
kind: List
items:
  - apiVersion: argoproj.io/v1alpha1
    kind: Application
    metadata:
      name: microservice-intg
    spec:
      destination:
        namespace: "microservice-intg"
        server: "https://kubernetes.default.svc"
      source:
        path: wiki-game
        repoURL: "git@github.com:aachermann/g04-infra.git"
        targetRevision: main
      project: microservice
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
  # - apiVersion: argoproj.io/v1alpha1
  #   kind: Application
  #   metadata:
  #     name: microservices-prod
  #   spec:
  #     destination:
  #       namespace: "microservice-prod"
  #       server: "https://kubernetes.default.svc"
  #     source:
  #       path: wiki-game/prod
  #       repoURL: "git@github.com:aachermann/g04-infra.git"
  #       targetRevision: main
  #     project: microservice
  #     syncPolicy:
  #       automated:
  #         prune: true
  #         selfHeal: true