apiVersion: v1
kind: List
items:
  - apiVersion: argoproj.io/v1alpha1
    kind: Application
    metadata:
      name: argocd
    spec:
      destination:
        namespace: argocd
        server: "https://kubernetes.default.svc"
      source:
        path: base
        repoURL: "git@github.com:aachermann/g04-infra.git"
        targetRevision: main
      project: devops
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
  - apiVersion: argoproj.io/v1alpha1
    kind: Application
    metadata:
      name: wikigame-intg
    spec:
      destination:
        namespace: "wikigame-intg"
        server: "https://kubernetes.default.svc"
      source:
        path: wiki-game/intg
        repoURL: "git@github.com:aachermann/g04-infra.git"
        targetRevision: main
      project: devops
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
  - apiVersion: argoproj.io/v1alpha1
    kind: Application
    metadata:
      name: wikigame-prod
    spec:
      destination:
        namespace: "wikigame-prod"
        server: "https://kubernetes.default.svc"
      source:
        path: wiki-game/prod
        repoURL: "git@github.com:aachermann/g04-infra.git"
        targetRevision: main
      project: devops
  - apiVersion: argoproj.io/v1alpha1
    kind: Application
    metadata:
      name: monitoring
    spec:
      destination:
        namespace: "monitoring"
        server: "https://kubernetes.default.svc"
      source:
        path: monitoring
        repoURL: "git@github.com:aachermann/g04-infra.git"
        targetRevision: main
      project: devops
      
