---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitlab-registry
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgAqLcihOTQG6HMzviRBGdsLV+/cE2goN/nHqq2PTSpfCbTZutos7wPCW+mJsDVpPTxor2EdPqlVa/5HAHaJ0XJwALu4XxplnMT8mNcI5FDDrBnqybHFhKk8/QHNobXeuWrVsyXZLGO2B0C0Euxt1dY/+vePv1HVhtzTW64T9nAVR0PmEKD1zhlJSwCd4Wx/WjIcNtQlThjFK63n0EMO771Oc74vgmrGIqQOgt06WjaiGDC08agmSA5IVRv8I0ug6CI2VIzmwZch1j0Us2IBcMJL6JoaAhvnkPy7UY/47cFt2/UZQrZqEMgZ6t9HPqWqFSXuIrj867aWZsVdcDuWlA/asnz6OYxwvO4xmvgNivmt0YCJoczSzbyS+Y7FbpvpJu6QLTdk7hUX3ZRj+sHsHzjaYUJ61sZVG81zdOVususevN10/HpNECVKqHnA73z7hN0FOe+1l4psngxWEjK5g+UDGlNhCOURCNdIW7hebyKnaPM//cJk4C/STMHhN8YbiGtIY3s5qMrq4lsm648vaO6eV4fwo+iLCiU1k8w7DMAZReEwk4PRR7ewTlIpQZr2Xrs54S2Mlg0Dcn1i0I9iCFB7FL7E6y/WWEYqOgVs/VFTe2T4Iffk1tc7u6oJ5+cyDaisIB1ql7JEJ2vckoST8p/DGwTbUzb7aHOm7Fu3naY2frCOJuT3mZh8PVhVpUGN6Qj8lVHKqAmRMw9li7J0QfdBQqyV8BydU08XrGk/zTPjEWYtlATmvwqNlK+N+TlHmaj4nAvDCo4efIzuPbf/UWW4cnHiCztrTeFj+jYk9vH3KtEBDbOqbSl5OERnAAXLoT8fC7WUYP4uGptm3va6B/7sGYIc//MJ14/WRfomhpbTdNwhHTRXpWAgcjbT73C03vGonCEbtXMYWCcRNsOVCSOt2Vrj/nAqIOlmPo6KTlWs+aUC+gi5PJHv+nwzb7bmig==
  template:
    metadata:
      creationTimestamp: null
      name: gitlab-registry
      namespace: default
    type: kubernetes.io/dockerconfigjson
