apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: devops
spec:
  orphanedResources:
    warn: false
  description: devops project
  sourceRepos:
    - "git@github.com:aachermann/g04-infra.git"
  destinations:
    - namespace: "wikigame-prod"
      server: https://kubernetes.default.svc
    - namespace: "wikigame-intg"
      server: https://kubernetes.default.svc
    - namespace: "argocd"
      server: https://kubernetes.default.svc