apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# overlay resources for devops teams
resources:
  # project/s
  - appprojects/appprojects.yaml
  # application/s
  - applications/application_list.yaml
  # (sealed)secret/s, e.g. argocd key for argocd resources and your argocd repository
  #- sealedsecrets/sealedsecret_gitlab-access-token.yaml
  #- sealedsecrets/sealedsecret_gitlab-ssh-key.yaml
  - sealedsecrets/sealedsecret_gitlab_registry.yaml

# patches:
#   - path: ./patches/patch_argocd.yaml